export const YOUTUBE_CAPABILITIES = {
  platform: 'youtube',
  name: 'YouTube',
  supportsRealLike: true,
  supportsRealComment: true,
  supportsRealSubscribe: true,
  supportsRealSave: true,
  supportsRealShare: true,
  supportsIframePlayback: true,
  supportsPublicStats: true,
  savePlaylistName: 'Content Test Lab Saves',
  scopes: [
    'https://www.googleapis.com/auth/youtube.force-ssl',
    'https://www.googleapis.com/auth/youtube.readonly',
    'openid',
    'profile',
    'email',
  ],
  labels: {
    like: 'Like',
    liked: 'Liked',
    comment: 'Comment',
    commented: 'Commented',
    share: 'Share',
    shared: 'Shared',
    save: 'Save',
    saved: 'Saved to Content Test Lab Saves',
    subscribe: 'Subscribe',
    subscribed: 'Subscribed',
  },
};
